---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-3-Clause
# Copyright © 2023, Serguei E. Leontiev (leo@sai.msu.ru)
#
name: Python yamllint test

on: push  # yamllint disable-line rule:truthy

jobs:
  lint:
    strategy:
      fail-fast: false  # TODO true
      matrix:
        os: ["macos", "ubuntu", "windows"]

    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v3

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint .github YAML files
        run: yamllint .github

      - name: False positive greek.yml
        run: |
          python -c "import locale; \
                     print(locale.getlocale(), \
                           locale.getpreferredencoding())"

          if [ "${{ matrix.os }}" == "windows" ] ; then
            if yamllint greek.yml ; then
              echo "XPASS: windows locales"
              exit 10
            else
              echo "XFAIL: ('English_United States', '1252') cp1252"
            fi
          else
            yamllint greek.yml
            echo "OK: greek.yml on macOS/Linux UTF-8"

            if [ "${{ matrix.os }}" == "ubuntu" ] ; then
              sudo localedef -f CP1251 -i ru_RU ru_RU.CP1251
            fi
            export LANG=ru_RU.CP1251
            export LC_ALL=ru_RU.CP1251
            locale

            python -c "import locale; \
                       print(locale.getlocale(), \
                             locale.getpreferredencoding())"
            if yamllint greek.yml ; then
              echo "XPASS: greek.yml on macOS/Linux ru_RU.CP1251"
              exit 20
            else
              echo "XFAIL: greek.yml on macOS/Linux ru_RU.CP1251"
            fi
          fi

      - name: False negative cp1252.yml
        run: |
          if [ "${{ matrix.os }}" == "windows" ] ; then
            if yamllint cp1252.yml ; then
              echo "XFAIL: ('English_United States', '1252') cp1252"
            else
              echo "XPASS: windows locales"
              exit 30
            fi
          else
            if yamllint cp1252.yml ; then
              echo "FAIL: cp1252.yml on macOS/Linux UTF-8"
              exit 40
            else
              echo "OK: cp1252.yml on macOS/Linux UTF-8"
            fi

            if [ "${{ matrix.os }}" == "ubuntu" ] ; then
              sudo localedef -f ISO-8859-1 -i en_US en_US.ISO8859-1
            fi
            export LANG=en_US.ISO8859-1
            export LC_ALL=en_US.ISO8859-1

            if yamllint cp1252.yml ; then
              echo "XFAIL: cp1252.yml on macOS/Linux en_US.ISO8859-1"
            else
              echo "XPASS: cp1252.yml on macOS/Linux en_US.ISO8859-1"
              exit 50
            fi
          fi

      - name: Workaround
        run: |
          export PYTHONUTF8=0
          export LANG=C
          export LC_ALL=C
          case "${{ matrix.os }}" in
            "windows")
              workaround="PYTHONUTF8=1"  # WARNING: Python 3.7+ only
              ;;
            "ubuntu")
              workaround="LANG=en_US.utf8 LC_ALL=en_US.utf8"
              ;;
            "macos")
              workaround="LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8"
              ;;
          esac
          eval $workaround yamllint greek.yml
          echo "OK: workaround greek.yml"
          if eval $workaround yamllint cp1252.yml ; then
            echo "FAIL: workaround cp1252.yml"
          else
            echo "OK: workaround cp1252.yml"
          fi
...
