---
name: Main

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
...
